name: Check Go Version Consistency

on:
  pull_request:
  push:

jobs:
  check-versions:
    permissions:
      contents: read
      pull-requests: write

    name: Check Go versions
    uses: joselsegura/processing-tools/.github/workflows/check-go-versions.yml@check_go_version
